votes
id INT PRIMARY KEY AUTO_INCREMENT
voter_id INT UNIQUE NOT NULL
candidate_id INT NOT NULL
date DATETIME NOT NULL

voters
id INT PRIMARY KEY AUTO_INCREMENT
name VARCHAR(255) NOT NULL
last_name VARCHAR(255) NOT NULL
document VARCHAR(8) UNIQUE NOT NULL
dob DATE NOT NULL
is_candidate BOOLEAN NOT NULL
address VARCHAR(255) NOT NULL
telephone_number VARCHAR(255) NOT NULL
sex VARCHAR(255) NOT NULL

candidate
id INT PRIMARY KEY AUTO_INCREMENT
voter_id  (CLAVE FORANEA a voters.id)

admins
id INT PRIMARY KEY AUTO_INCREMENT
name VARCHAR(255) NOT NULL
last_name VARCHAR(255) NOT NULL
email VARCHAR(255) UNIQUE NOT NULL
password VARCHAR(255) NOT NULL